version: '3'
services:
  redis:
    build: services/redis/
    volumes:
      - ./services/redis:/data
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  search:
    build:
      context: ./
      dockerfile: services/search/Dockerfile
    volumes:
      - ./services/search:/app
      - ./shared:/app/shared
      - ./praw.ini:/app/praw.ini
    environment:
      - CONFIG=${CONFIG}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: python -u search.py

  filter:
    build:
      context: ./
      dockerfile: services/filter/Dockerfile
    volumes:
      - ./services/filter:/app
      - ./shared:/app/shared
      - ./praw.ini:/app/praw.ini
    environment:
      - CONFIG=${CONFIG}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: python -u filter.py

  upload:
    build:
      context: ./
      dockerfile: services/upload/Dockerfile
    volumes:
      - ./services/upload:/app
      - ./shared:/app/shared
    environment:
      - CONFIG=${CONFIG}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: python -u upload.py

  reply:
    build:
      context: ./
      dockerfile: services/reply/Dockerfile
    volumes:
      - ./services/reply:/app
      - ./shared:/app/shared
      - ./praw.ini:/app/praw.ini
    environment:
      - CONFIG=${CONFIG}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: python3 -u reply.py

